// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0QuxZOGNqiOB-eVKmrcMh1HRzClCLUBo',
    appId: '1:736553377161:web:4f4c5c9ac966afe2b45558',
    messagingSenderId: '736553377161',
    projectId: 'chatapp-76361',
    authDomain: 'chatapp-76361.firebaseapp.com',
    storageBucket: 'chatapp-76361.appspot.com',
    measurementId: 'G-9MG57BFPLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzZsCcbXpILTyw6QFp16K1nYcJUWd8PMA',
    appId: '1:736553377161:android:ea9d5dcc352073cab45558',
    messagingSenderId: '736553377161',
    projectId: 'chatapp-76361',
    storageBucket: 'chatapp-76361.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM39sK6x3k0ir5H7hRedD8_8F1O10vkLI',
    appId: '1:736553377161:ios:7c2c96b508d79e71b45558',
    messagingSenderId: '736553377161',
    projectId: 'chatapp-76361',
    storageBucket: 'chatapp-76361.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM39sK6x3k0ir5H7hRedD8_8F1O10vkLI',
    appId: '1:736553377161:ios:96ee91ecd367e24ab45558',
    messagingSenderId: '736553377161',
    projectId: 'chatapp-76361',
    storageBucket: 'chatapp-76361.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
